defaults:
  - scope:
      path: "images"
    values:
      image: true

title: "Sem pânico!"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
logo: "/images/logo.png"
## baseurl: ""
## url: "https://lizzymartin.github.io"